spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8089/
          predicates:
            - Path= /customers/**
        - id : r2
          uri : http://localhost:8082/
          predicates:
            - Path= /products/**
#on peut faire cette partie dans application.propertise
    discovery:
      enabled: false
  application:
    name: gateway-service
server:
  port: 8888
